#
# Copyright (c) 2025 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#

# This indicates if the chart is being deployed to an OpenShift or Kind cluster. Valid values are `openshift` and `kind`
variant: kind

# This defines the cert-manager issuer that will be used for the certificates used by Keycloak. The default is to use
# the cluster issuer that is automatically created for the Kind cluster used for integration tests.
issuerRef:
  kind: ClusterIssuer
  name: default-ca
