// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/innabox/fulfillment-service/internal/auth (interfaces: OwnershipLogic)
//
// Generated by this command:
//
//	mockgen -destination=ownership_logic_mock.go -package=auth . OwnershipLogic
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOwnershipLogic is a mock of OwnershipLogic interface.
type MockOwnershipLogic struct {
	ctrl     *gomock.Controller
	recorder *MockOwnershipLogicMockRecorder
	isgomock struct{}
}

// MockOwnershipLogicMockRecorder is the mock recorder for MockOwnershipLogic.
type MockOwnershipLogicMockRecorder struct {
	mock *MockOwnershipLogic
}

// NewMockOwnershipLogic creates a new mock instance.
func NewMockOwnershipLogic(ctrl *gomock.Controller) *MockOwnershipLogic {
	mock := &MockOwnershipLogic{ctrl: ctrl}
	mock.recorder = &MockOwnershipLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnershipLogic) EXPECT() *MockOwnershipLogicMockRecorder {
	return m.recorder
}

// DetermineAssignedOwners mocks base method.
func (m *MockOwnershipLogic) DetermineAssignedOwners(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetermineAssignedOwners", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetermineAssignedOwners indicates an expected call of DetermineAssignedOwners.
func (mr *MockOwnershipLogicMockRecorder) DetermineAssignedOwners(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetermineAssignedOwners", reflect.TypeOf((*MockOwnershipLogic)(nil).DetermineAssignedOwners), ctx)
}
